### PR TITLE
fix references

### PR DESCRIPTION
**Pull request by vshanks-cydarm**

### CODE REVIEW

**Comment by mateusdz** [comment]
Dear Vaughan Shanks,

Thank you for noticing and fixing the problem.
 
Having said that. For now, I highly recommend utilizing the schemas from the "cacao-v1.0-cs02" branch as they are, according to us, complete and follow the last published CACAO spec (Committee Specification 02) a.k.a. the last stable release.  
Regarding the "working" branch, we have not updated it yet, as we focused on finishing the "cacao-v1.0-cs02" version. 
We aim to update the "working" branch soon. However, the branch will not be stable until the next CACAO specification release. 

Best regards, 
Mateusz Zych

**Review by mateusdz — CHANGES_REQUESTED** [review]
According to the JSON schema specification (https://json-schema.org/understanding-json-schema/structuring.html#id) the $id should contain the absolute path to be able to retrieve the schemas. This property is what sets the baseURL of the schema. Possibly this is just a select and change-all mistake.

So all the $id values should remain the same, and thereafter all the $refs should contain the relative path starting from the current file/baseURL. 

I would gladly receive and follow-up pull request. Otherwise, I will consider your feedback and update the schemas in the following days.

**Comment by vshanks-cydarm** [comment]
Hi Mateusdz,

Thanks for the feedback. I have updated the ids to be full URLs against the "cacao-v1.0-cs02" branch, with all refs as relative paths.

I was unable to use the current "cacao-v1.0-cs02" version of the schemas as-is due to inconsistencies between ids and refs, and I thought that using relative paths would be an improvement.

For the commit I just pushed, I have been able to load the schemas into VSCode and validate some example CACAO playbooks, whereas previously I was seeing errors.

I hope this contribution is useful!

**Comment by mateusdz** [comment]
Hi Vaughan,

Since the PR exists in the "working" branch, the $id should contain the path to a file within the working branch. E.g.:   
"https://raw.githubusercontent.com/fovea-research/cacao-json-schemas/working/schemas/commands/command.json"
and not 
"https://raw.githubusercontent.com/fovea-research/cacao-json-schemas/cacao-v1.0-cs02/schemas/commands/command.json"

All $refs need to have a relative path from the current file path. E.g., For trying to use the identifier.json from data-marking.json, we need to go up a folder, then down to data-types, then to identifier.json. So the $ref will be as follow: 
"$ref": "../data-types/identifier.json"
This means that all $refs (other than $refs in playbook.json) need to be changed accordingly. 

I consider using relative paths as an improvement as they reduce the number of URLs to maintain. Thanks for pitching this idea. I will gladly implement this idea of relative paths in the cacao-v1.0-cs02 branch. 

Best, 
Mateusz

**Review by mateusdz — CHANGES_REQUESTED** [review]
Hi Vaughan,

Since the PR exists in the "working" branch, the $id should contain the path to a file within the working branch. E.g.:
"https://raw.githubusercontent.com/fovea-research/cacao-json-schemas/working/schemas/commands/command.json"
and not
"https://raw.githubusercontent.com/fovea-research/cacao-json-schemas/cacao-v1.0-cs02/schemas/commands/command.json"

All $refs need to have a relative path from the current file path. E.g., For trying to use the identifier.json from data-marking.json, we need to go up a folder, then down to data-types, then to identifier.json. So the $ref will be as follow:
"$ref": "../data-types/identifier.json"
This means that all $refs (other than $refs in playbook.json) need to be changed accordingly.

I consider using relative paths as an improvement as they reduce the number of URLs to maintain. Thanks for pitching this idea. I will gladly implement this idea of relative paths in the cacao-v1.0-cs02 branch.

Best,
Mateusz

**Comment by vshanks-cydarm** [comment]
Thanks again for the feedback, Mateusz. I think I have covered off on all the relative paths now.

**Review by mateusdz — COMMENTED** [review]
Hi, that looks good! Thank you for your contribution, Vaughan.

**Comment by mateusdz** [comment]
FYI,
after reviewing your changes, I noticed a different bug regarding using target.json (a parent/super class) as a data type in action.json and attacker.json instead of "oneOf" the child classes. I am working on a PR to fix that issue.

**Comment by vshanks-cydarm** [comment]
Thanks Mateusz, grateful for the chance to contribute something!

**Pull request merged**
